using Albatross.CommandLine;
using Albatross.SemanticConsole.Tool.AutoGenerated;
using Albatross.SemanticConsole.Spectre;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System.CommandLine;

namespace Albatross.SemanticConsole.Tool {
	internal class Program {
		static async Task<int> Main(string[] args) {
			await using var host = new CommandHost("Semantic Console")
				.ConfigureHost(builder => builder.ConfigureLogging(logging => logging.ClearProviders()))
				.RegisterServices(RegisterServices)
				.AddCommands()
				.Parse(args)
				.Build();
			return await host.InvokeAsync();
		}

		static void RegisterServices(ParseResult result, IServiceCollection services) {
			services.RegisterCommands();
			services.AddSpectreConsole();
		}
	}
}