<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Spectre.Console" Version="0.57.2" />
		<PackageReference Include="Albatross.CommandLine" Version="9.0.0-rc.284" />
	</ItemGroup>

</Project>
